version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - export NODE_VERSION=$(<.nvmrc)
      - nvm install "$NODE_VERSION"
      - nvm use "$NODE_VERSION"
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - echo building the app...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
